# Generated by Django 4.0.3 on 2022-04-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv',
            old_name='file_nane',
            new_name='file_name',
        ),
    ]
